import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
        <script defer data-domain="signupy.com" src="https://plausible.io/js/plausible.js"></script>
      </Head>

      <main>
      <h1 className="text-3xl font-bold">
        Contact people everywhere
      </h1>
      <p>Mailing list</p>
      Sign up to ours
      </main>

      <footer>
      </footer>
    </div>
  )
}
